version: '3'

services:
  lg-west-1:
    image: opentsx/time-series-generator:3.0.1
    hostname: lg-west-1
    container_name: lg-west-1
    networks:
      - n1
    volumes:
      - ./config/:/etc/opentsx/config/
      - ./bin/:/opentsx-lg/bin/
    environment:
      OPENTSX_TOPIC_MAP_FILE_NAME: "/etc/opentsx/config/topiclist.def"
      OPENTSX_PRIMARY_CLUSTER_CLIENT_CFG_FILE_NAME: "/etc/opentsx/config/ccloud.props"
      #OPENTSX_PRIMARY_CLUSTER_CLIENT_CFG_FILE_NAME: "/etc/opentsx/config/cuh.props"
      #OPENTSX_PRIMARY_CLUSTER_CLIENT_CFG_FILE_NAME: "/etc/opentsx/config/cpl.props"
      OPENTSX_SHOW_GUI: "false"
    extra_hosts:
      - "broker-west-5:${MDC1}"
      - "broker-west-6:${MDC1}"
      - "broker-west-7:${MDC1}"
      - "broker-west-1:${MDC2}"
      - "broker-west-2:${MDC2}"
      - "broker-east-3:${MDC2}"
      - "broker-east-4:${MDC2}"
      - "zookeeper-central:${MDC2}"
      - "zookeeper-east:${MDC2}"
      - "zookeeper-west:${MDC2}"
      - "broker-east-8:${MDC3}"
      - "broker-east-9:${MDC3}"
      - "broker-east-10:${MDC3}"
      - "schema-registry-west-1:${MDC2}"
    entrypoint: /opentsx-lg/bin/executor-script.sh
    tty: false

networks:
  n1:
