apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: control-center
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: control-center
    spec:
      containers:
      - env:
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: connect:8083
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
          value: http://localhost:8088
        - name: CONTROL_CENTER_KSQL_URL
          value: http://ksql-server:8088
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry:8081
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: PORT
          value: "9021"
        image: confluentinc/cp-enterprise-control-center:5.4.0
        imagePullPolicy: ""
        name: control-center
        ports:
        - containerPort: 9021
        resources: {}
      hostname: control-center
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
