apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-server
  name: ksql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksql-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-server
    spec:
      containers:
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: KSQL_CACHE_MAX_BYTES_BUFFERING
          value: "0"
        - name: KSQL_CONFIG_DIR
          value: /etc/ksql
        - name: KSQL_CONSUMER_INTERCEPTOR_CLASSES
          value: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
        - name: KSQL_HOST_NAME
          value: ksql-server
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: http://schema-registry:8081
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
        - name: KSQL_PRODUCER_INTERCEPTOR_CLASSES
          value: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
        image: confluentinc/cp-ksql-server:5.4.0
        imagePullPolicy: ""
        name: ksql-server
        ports:
        - containerPort: 8088
        resources: {}
      hostname: ksql-server
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
